services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80" 

    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}